minimumReleaseAgeExcludePrune: true
trustPolicy: no-downgrade
shellEmulator: true

overrides:
  zod: 3.25.76

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi
  - workerd

onlyBuiltDependencies:
  - better-sqlite3
