<script lang="ts" setup>
import { Analytics } from '@vercel/analytics/vue'
import { SpeedInsights } from '@vercel/speed-insights/vue'

// Icon set generated by `nuxt-seo-utils icons` from public/profile.png.
// nuxt-seo-utils does NOT inject these tags itself, so they are declared here.
useHead({
  meta: [
    // Google Search Console ownership verification. Must be live on the deployed
    // site before pressing "Verify" there.
    { name: 'google-site-verification', content: 'YSz_WPB5W_oC0OtQ3jPWbaciJ7V9Tak5Voh7tPchb6E' },
  ],
  link: [
    { rel: 'icon', href: '/favicon.ico', sizes: '48x48' },
    { rel: 'icon', type: 'image/png', sizes: '32x32', href: '/icon-32x32.png' },
    { rel: 'icon', type: 'image/png', sizes: '16x16', href: '/icon-16x16.png' },
    { rel: 'apple-touch-icon', sizes: '180x180', href: '/apple-touch-icon.png' },
  ],
})

// Single static share image (public/og.png), served with an ABSOLUTE url
// because social crawlers ignore relative image paths.
//
// Use the CONFIGURED site url, not `useRequestURL()`: the site is prerendered
// (nitro.prerender.crawlLinks), so there is no request at build time and the
// origin resolved to "http://localhost" in production.
const ogImage = `${useSiteConfig().url}/og.png`

useSeoMeta({
  // nuxt-seo-utils appends "• <site.name>" to every title, and site.name is
  // "Yurier Herrera" — so any title that already contains the name rendered it
  // twice. Each page writes its own complete, name-bearing title instead.
  titleTemplate: '%s',
  ogImage,
  ogImageWidth: 1200,
  ogImageHeight: 630,
  ogImageAlt: 'Yurier Herrera — Software Engineer & Entrepreneur',
})

const route = useRoute()
const { messages } = useChatStore()
const head = useLocaleHead()
</script>

<template>
  <UApp>
    <Html :lang="head.htmlAttrs.lang" :dir="head.htmlAttrs.dir">
      <Head>
        <template v-for="link in head.link" :key="link.key">
          <Link :id="link.key" :rel="link.rel" :href="link.href" :hreflang="link.hreflang" />
        </template>
        <template v-for="meta in head.meta" :key="meta.key">
          <Meta :id="meta.key" :property="meta.property" :content="meta.content" />
        </template>
      </Head>
      <Body>
        <slot />
      </Body>
    </Html>
    <NuxtLoadingIndicator color="#808080" />
    <AppBackground />
    <ChatCommandPalette
      v-motion
      :active="messages.length > 0"
      :mode="route.path.includes('/projects') || route.path.includes('/writings') ? 'work' : 'chat'"
      :initial="{
        opacity: 0,
        y: 200,
        scale: 0.6,
      }"
      :enter="{
        opacity: 1,
        y: 0,
        scale: 1,
        transition: {
          delay: route.path === '/' ? 1800 : 0,
          ease: 'easeIn',
        },
      }"
    />
    <NuxtPage />
    <Analytics />
    <SpeedInsights />
  </UApp>
</template>

<style>
@reference "@/assets/css/main.css";

/* Transition switcher */
.page-enter-active,
.page-leave-active {
  transition: all 0.2s;
}

.page-leave-to {
  opacity: 0;
  transform: translateY(-5px);
}

.page-enter-from {
  opacity: 0;
  transform: translateY(5px);
}

/* Theme switcher */
::view-transition-old(root),
::view-transition-new(root) {
  animation: none;
  mix-blend-mode: normal;
}
::view-transition-old(root) {
  z-index: 1;
}
::view-transition-new(root) {
  z-index: 9999;
}
.dark::view-transition-old(root) {
  z-index: 9999;
}
.dark::view-transition-new(root) {
  z-index: 1;
}
</style>
