<script lang="ts" setup>
import { Analytics } from '@vercel/analytics/vue'
import { SpeedInsights } from '@vercel/speed-insights/vue'

// Icon set generated by `nuxt-seo-utils icons` from public/profile.png.
// nuxt-seo-utils does NOT inject these tags itself, so they are declared here.
useHead({
  link: [
    { rel: 'icon', href: '/favicon.ico', sizes: '48x48' },
    { rel: 'icon', type: 'image/png', sizes: '32x32', href: '/icon-32x32.png' },
    { rel: 'icon', type: 'image/png', sizes: '16x16', href: '/icon-16x16.png' },
    { rel: 'apple-touch-icon', sizes: '180x180', href: '/apple-touch-icon.png' },
  ],
})

useSeoMeta({
  // nuxt-seo-utils appends "• <site.name>" to every title, and site.name is
  // "Yurier Herrera" — so any title that already contains the name rendered it
  // twice. Each page writes its own complete, name-bearing title instead.
  titleTemplate: '%s',
  // og:image is owned by nuxt-og-image (see defineOgImage calls per page).
})

// Global fallback share image: nuxt-og-image v6 removed `defaults.component`,
// so pages without their own defineOgImage() would emit no og:image at all.
// The payload registry is keyed by "og", so a page-level call overrides this.
// The brand footer is redundant on the home image, where the name IS the title,
// so it is hidden there via an empty `footer`.
defineOgImage('OgImagePortfolio', {
  title: 'Yurier Herrera',
  subtitle: 'UX-obsessed products · AI & automation',
  // An empty string is dropped during props serialization, so the component's
  // default footer would come back. Use a complementary line instead.
  footer: 'Open to collaboration',
})

const route = useRoute()
const { messages } = useChatStore()
const head = useLocaleHead()
</script>

<template>
  <UApp>
    <Html :lang="head.htmlAttrs.lang" :dir="head.htmlAttrs.dir">
      <Head>
        <template v-for="link in head.link" :key="link.key">
          <Link :id="link.key" :rel="link.rel" :href="link.href" :hreflang="link.hreflang" />
        </template>
        <template v-for="meta in head.meta" :key="meta.key">
          <Meta :id="meta.key" :property="meta.property" :content="meta.content" />
        </template>
      </Head>
      <Body>
        <slot />
      </Body>
    </Html>
    <NuxtLoadingIndicator color="#808080" />
    <AppBackground />
    <ChatCommandPalette
      v-motion
      :active="messages.length > 0"
      :mode="route.path.includes('/projects') || route.path.includes('/writings') ? 'work' : 'chat'"
      :initial="{
        opacity: 0,
        y: 200,
        scale: 0.6,
      }"
      :enter="{
        opacity: 1,
        y: 0,
        scale: 1,
        transition: {
          delay: route.path === '/' ? 1800 : 0,
          ease: 'easeIn',
        },
      }"
    />
    <NuxtPage />
    <Analytics />
    <SpeedInsights />
  </UApp>
</template>

<style>
@reference "@/assets/css/main.css";

/* Transition switcher */
.page-enter-active,
.page-leave-active {
  transition: all 0.2s;
}

.page-leave-to {
  opacity: 0;
  transform: translateY(-5px);
}

.page-enter-from {
  opacity: 0;
  transform: translateY(5px);
}

/* Theme switcher */
::view-transition-old(root),
::view-transition-new(root) {
  animation: none;
  mix-blend-mode: normal;
}
::view-transition-old(root) {
  z-index: 1;
}
::view-transition-new(root) {
  z-index: 9999;
}
.dark::view-transition-old(root) {
  z-index: 9999;
}
.dark::view-transition-new(root) {
  z-index: 1;
}
</style>
